### ISSUE TITLE
Killed the Rocketry, Spacecraft and Special Projects pages

### ISSUE THREAD

**Issue by alienorlgrst** [spaceconcordia/spaceconcordia.github.io#10]
I had thought the dropdown menues were also clickable and acted as regular buttons. But they don't. There's now no way of accessing the main division pages. 
I don't know how to make the dropdown items also act like a regular button..

#alibreaksthings
#plzfixit

**Comment by PeterGhimself** [comment]
started development on [reviveTeamPages-10](/spaceconcordia/spaceconcordia.github.io/tree/reviveTeamPages-10)

I managed to fix the issue.. I still need to do a tiny bit of cleaning up/refactoring

**Comment by PeterGhimself** [comment]
Never mind it's too much work I'd have to edit all the html files o.O
I'll just open a PR now.
The code base needs serious refactoring/reorganization... I'll write up some more issues regarding that later today.

**Comment by alienorlgrst** [comment]
It's actually all dropdowns**, divisions special projects contact us and about us

**Comment by n0pan** [comment]
Yup... the code base definitely needs serious refactoring. The menu should be in its own file and be injected into all of the static pages to make it easier to edit.

**Comment by PeterGhimself** [comment]
@n0pan I was gonna make an issue for this injecting... in general, I'd like make a function called `initUI` which will do this for every module... Also I'm gonna move the files into folders for clearer organization.. I'll make a separate issue for that.
I'm closing this issue now, even though I'll merge the branch later tonight.
