### ISSUE TITLE
Exec page - few photos missing that are already there

### ISSUE THREAD

**Issue by PeterGhimself** [spaceconcordia/spaceconcordia.github.io#8]
There is a tab for the `2016-2017` team, and the `2017-2018` team.
There are a few members who are in both, but in one case they have a photo, in the other they don't.
This shouldn't be such a hard issue to deal with. Specifically this applies to Michael Li and Mark Snidal.

![execteam1](https://user-images.githubusercontent.com/19865282/29950710-a878e942-8e8b-11e7-93fd-549331d7170c.PNG)

![execteam2](https://user-images.githubusercontent.com/19865282/29950714-ae40f41e-8e8b-11e7-9b4c-c6741796bb78.PNG)

**Comment by alienorlgrst** [comment]
The background or the photos is not the same, I don't want to mix them tbh.

**Comment by PeterGhimself** [comment]
Ah ok, this is why it is good to open issues first before starting work on branches. I will close this issue then, as discussed on slack.
